```{r}
library(tidyverse) 
library(lubridate)
datos<-read_delim("datos.csv",delim=";")
```
```{r}
library(data.table)
datos <- as.data.table(datos)
datos <- datos[, lapply(.SD, iconv, "latin1", "UTF-8")]
```


Parte 1
```{r}
datos %>% mutate(fecha=ym(TIEM_DIA_SK_INCAUTACION)) %>% 
group_by(TINC_TINC_DESCC,fecha,PAIS_PAIS_DESCC_PAIS_PROCEDENC) %>% summarise(conteo=n()) %>% subset(subset=grepl("ARMAS Y SUS ACCESORIOS",TINC_TINC_DESCC)) %>% ggplot()+geom_boxplot(aes(x=PAIS_PAIS_DESCC_PAIS_PROCEDENC,y=conteo))
#solo primer articulo segun pais
```
```{r}
datos%>% mutate(fecha=ym(TIEM_DIA_SK_INCAUTACION)) %>% group_by(TINC_TINC_DESCC,fecha) %>% summarise(conteo=n())  %>% subset(subset=grepl("ARMAS Y SUS ACCESORIOS",TINC_TINC_DESCC)) %>% ggplot(aes(x=fecha,y=conteo))+geom_line()
#2 primeros articulos evolucion total
```
```{r}
datos%>% mutate(fecha=ym(TIEM_DIA_SK_INCAUTACION)) %>%group_by(TINC_TINC_DESCC,fecha) %>% summarise(conteo=n()) %>%filter(TINC_TINC_DESCC %in% c("ANTEOJOS","BIJOU")) %>% ggplot(aes(x=fecha,y=conteo))+geom_line()+facet_wrap(~TINC_TINC_DESCC)
#intento de elegir articulo
```

Parte 3
```{r}
datos%>%group_by(ADUA_ADUA_DESCC) %>% summarise(conteo=n()) %>% ggplot(aes(x=fct_reorder(ADUA_ADUA_DESCC,conteo),y=conteo))+geom_col()
```

Parte 2
```{r}
datos %>% separate(TIEM_DIA_SK_INCAUTACION, into=c("anio","mes"),sep=4) %>%group_by(INFR_INFR_DESCC,anio) %>% summarise(conteo=n()) %>% ggplot(aes(x=anio,y=conteo))+geom_col()+facet_wrap(~INFR_INFR_DESCC,scales="free")
```

```{r}
hola<-datos %>% group_by(TINC_TINC_DESCC) %>% summarise(conteo=n())
tipos<-as.vector(hola[,1])
tipos
```

```{r}
datos %>% mutate(fecha=ym(TIEM_DIA_SK_INCAUTACION)) %>% 
group_by(TINC_TINC_DESCC,fecha,PAIS_PAIS_DESCC_PAIS_PROCEDENC) %>% summarise(conteo=n()) %>% subset(subset=grepl("ARMAS Y SUS ACCESORIOS",TINC_TINC_DESCC)) %>% ggplot()+geom_boxplot(aes(x=reorder(PAIS_PAIS_DESCC_PAIS_PROCEDENC,conteo,median),y=conteo))
```

```{r}
datos %>% filter(as.numeric(INC_VALOR_MN)<atipicovalor) %>%ggplot(aes(x=as.numeric(INC_VALOR_MN)))+geom_histogram()
```

```{r}
datos %>% group_by(ADUA_ADUA_DESCC,PAIS_PAIS_DESCC_PAIS_PROCEDENC) %>% summarise(conteo=n()) %>%ggplot()+geom_tile(aes(x=PAIS_PAIS_DESCC_PAIS_PROCEDENC,y=ADUA_ADUA_DESCC,fill=conteo))
```

```{r}
atipicovalor<-quantile(as.numeric(datos$INC_VALOR_MN),probs=0.75)+1.5*(quantile(as.numeric(datos$INC_VALOR_MN),probs=0.75)-quantile(as.numeric(datos$INC_VALOR_MN),probs=0.25))

atipicocantidad<-quantile(as.numeric(datos$INC_CANTIDAD),probs=0.75)+1.5*(quantile(as.numeric(datos$INC_CANTIDAD),probs=0.75)-quantile(as.numeric(datos$INC_CANTIDAD),probs=0.25))

datos %>% mutate(INC_CANTIDAD=round(as.numeric(INC_CANTIDAD),0),INC_VALOR_MN=round(as.numeric(INC_VALOR_MN),0))%>% filter(INC_VALOR_MN<atipicovalor)%>% filter(INC_CANTIDAD<atipicocantidad)%>% ggplot(aes(x=INC_VALOR_MN,y=INC_CANTIDAD))+geom_point(alpha=1/5)+theme(aspect.ratio = 1)+geom_smooth(method=lm)

#cor(as.numeric(datos$INC_CANTIDAD),as.numeric(datos$INC_VALOR_MN))
```
```{r}
datos %>% group_by(INFR_INFR_DESCC,ESTINC_ESTINC_DESCC) %>% summarise(conteo=n())
tabla<-data.frame(estado=c("Contencioso Final","Contencioso Inicial","Falsificacion","Ingresado","Valorador","Contencioso Final","Contencioso Inicial","Falsificacion","Ingresado","Valorador","Contencioso Final","Contencioso Inicial","Falsificacion","Ingresado","Valorador","Contencioso Final","Contencioso Inicial","Falsificacion","Ingresado","Valorador"),infraccion=c("Abandono","Abandono","Abandono","Abandono","Abandono","Contrabando","Contrabando","Contrabando","Contrabando","Contrabando","Falsificacion","Falsificacion","Falsificacion","Falsificacion","Falsificacion","Receptacion","Receptacion","Receptacion","Receptacion","Receptacion"),Freq=c(17362,399,365,438,2,54169,2090,1004,416,314,101,0,3,0,0,129,0,0,0,0))
ggplot(tabla,aes(x=estado,y=infraccion,fill=Freq))+geom_tile()+scale_fill_gradient(low="white",high="blue")
```

